import type { PlanetVisualConfig } from '../types/planet'

export const planetConfigs: PlanetVisualConfig[] = [
    {
        id: 'mercury',
        name: 'Mercury',
        color: '#a7a29a',
        radius: 0.38,
        orbitRadius: 7.5,
        orbitSpeed: 1.6,
        rotationSpeed: 0.012,
        emissive: '#5b5650',
        emissiveIntensity: 0.08,
    },
    {
        id: 'venus',
        name: 'Venus',
        color: '#d9b36c',
        radius: 0.62,
        orbitRadius: 10,
        orbitSpeed: 1.2,
        rotationSpeed: 0.008,
        emissive: '#7a5a2b',
        emissiveIntensity: 0.1,
    },
    {
        id: 'earth',
        name: 'Earth',
        color: '#4f83ff',
        radius: 0.65,
        orbitRadius: 12.8,
        orbitSpeed: 1,
        rotationSpeed: 0.02,
        emissive: '#1f4fbf',
        emissiveIntensity: 0.12,
    },
    {
        id: 'mars',
        name: 'Mars',
        color: '#c96a3d',
        radius: 0.5,
        orbitRadius: 15.8,
        orbitSpeed: 0.8,
        rotationSpeed: 0.018,
        emissive: '#7a3a1f',
        emissiveIntensity: 0.08,
    },
    {
        id: 'jupiter',
        name: 'Jupiter',
        color: '#d2b48c',
        radius: 1.45,
        orbitRadius: 21,
        orbitSpeed: 0.42,
        rotationSpeed: 0.04,
        emissive: '#8a6a52',
        emissiveIntensity: 0.06,
    },
    {
        id: 'saturn',
        name: 'Saturn',
        color: '#d8c08c',
        radius: 1.22,
        orbitRadius: 27,
        orbitSpeed: 0.3,
        rotationSpeed: 0.034,
        emissive: '#8c7a52',
        emissiveIntensity: 0.05,
        ring: {
        innerRadius: 1.55,
        outerRadius: 2.35,
        color: '#cbb892',
        opacity: 0.42,
        },
    },
    {
        id: 'uranus',
        name: 'Uranus',
        color: '#8fd6d1',
        radius: 0.95,
        orbitRadius: 33,
        orbitSpeed: 0.22,
        rotationSpeed: 0.026,
        emissive: '#4f8f8b',
        emissiveIntensity: 0.05,
    },
    {
        id: 'neptune',
        name: 'Neptune',
        color: '#4d6fff',
        radius: 0.92,
        orbitRadius: 38,
        orbitSpeed: 0.16,
        rotationSpeed: 0.024,
        emissive: '#243c9a',
        emissiveIntensity: 0.08,
    },
]